version: '3.1'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - todo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test@123
    networks:
      - todo_network
    hostname: mongohost  # Corrected here

  todoapp:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - todo_network

networks:
  todo_network:

volumes:
  todo-volume:


